server:
  port: 80
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true